---

- name: Pull from git
  git:
    repo: https://github.com/cryptopartydk/cryptoparty.dk.git
    version: "{{ git_version }}"
    dest: /srv/cryptoparty

- name: Set ownership of application directory
  file:
    state: directory
    recurse: yes
    owner: "{{ www_user }}"
    group: "{{ www_user }}"
    path: "/srv/cryptoparty"

- name: Install application requirements via pip
  pip:
    requirements: /srv/cryptoparty/requirements.txt
    chdir: /srv/cryptoparty
    executable: pip3
    virtualenv: /srv/cryptoparty/virtualenv
    virtualenv_command: pyvenv

- name: Application environment variables (.env)
  template:
    src: env.j2
    dest: /srv/cryptoparty/cryptoparty/.env

- name: uWSGI systemd service
  template:
    src: cryptoparty-uwsgi.service.j2
    dest: /lib/systemd/system/cryptoparty-uwsgi.service

- name: uWSGI configuration
  template:
    src: uwsgi_conf.ini.j2
    dest: /srv/cryptoparty/uwsgi_conf.ini

- name: Migrate database
  django_manage:
    app_path: /srv/cryptoparty/
    command: migrate
    virtualenv: /srv/cryptoparty/virtualenv/

- name: Collect static files
  django_manage:
    app_path: /srv/cryptoparty/
    command: collectstatic
    virtualenv: /srv/cryptoparty/virtualenv/

- name: Restart nginx
  service:
    name: nginx
    state: restarted

- name: Restart uWSGI
  service:
    name: cryptoparty-uwsgi
    state: restarted
