---
- name: Update and upgrade system via apt
  apt:
    update_cache: yes
    upgrade: full

- name: Install basic requirements
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - python3-dev
    - python3-pip
    - python3-venv
    - python-pip
    - python-dev
    - upstart
    - nginx
    - git

- name: Install uwsgi systemwide
  pip:
    name: uwsgi
    executable: pip3

- name: "Create {{ www_user }} group"
  group:
    name: "{{ www_user }}"

- name: "Create {{ www_user }} user"
  user:
    name: "{{ www_user }}"
    group: "{{ www_user }}"
