---
- include: nginx.yml
- include: letsencrypt.yml
- include: tor.yml

- name: Test nginx configuration
  command: /usr/sbin/nginx -t

- name: Restart nginx
  service:
    name: nginx
    state: restarted
